version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - "3000:3000"
    links: mongo
  mongo:
    image: "mongo"
    volumes: 
        - mongo-volumes:/data/db

volumes:
    db-data: